matrix:
  include:
    - language: android
      jdk: oraclejdk8
      android:
        components:
          - tools
          - android-27
          - build-tools-27.0.2
      licenses:
        - 'android-sdk-license-.+'
      before_install:
        - yes | sdkmanager "platforms;android-27"
      script:
        - ./gradlew android:build

    - language: java
      jdk: oraclejdk8
      script:
        - ./gradlew shadowJar createExe

    - language swift
      osx_image: xcode9.2
      xcode_project: iOS/PMMonitor.xcodeproj
      xcode_scheme: PMMonitor
