matrix:
  include:
    - language: android
      jdk: oraclejdk8
      android:
        components:
          - tools
          - android-27
          - build-tools-27.0.2
      script:
        - ./gradlew android:build

    - language: java
      jdk: oraclejdk8
      script:
        - ./gradlew shadowJar createExe
